label: 'Input'
title: 'Common - Input'
# status: 'done'
preview: '@preview'
context:
  input:
    id: 'inputId'
    label:
      hidden: true
      text: 'inputLabel'
    placeholder: 'inputPlaceholder'