label: 'Icons'
# status: 'done'
preview: '@preview'
collated: true
context:
  icon: 'icon-add'

variants:
  - name: 'icon-add-reverse'
    context:
      icon: 'icon-add-reverse'

  - name: 'icon-angle-left'
    context:
      icon: 'icon-angle-left'

  - name: 'icon-angle-right'
    context:
      icon: 'icon-angle-right'

  - name: 'icon-cross'
    context:
      icon: 'icon-cross'

  - name: 'icon-cross-bold'
    context:
      icon: 'icon-cross-bold'
