label: 'Search Box'
# status: 'done'
preview: '@preview'
context:
  input:
    id: 'inputId'
    type: 'search'
    label:
      hidden: false
      text: 'Search The Site'
    placeholder: 'Enter Keyword'
  button: 
    element: 'button'
    style: 'primary'
    text: 'search'
    label: 'search button'